ci: 🎡 added new ci actions

diff --git a/.github/workflows/tests-and-lint.yml b/.github/workflows/tests-and-lint.yml
--- a/.github/workflows/tests-and-lint.yml
+++ b/.github/workflows/tests-and-lint.yml
@@ -32,14 +32,49 @@ jobs:
       - name: Run Linter
         run: pnpm run lint
 
+      - name: Resolve package versions
+        id: resolve-package-versions
+        shell: bash
+        run: >
+          echo "$(
+          node -e "
+           const fs = require('fs');
+           const lockfile = fs.readFileSync('./pnpm-lock.yaml', 'utf8');
+           const pattern = (name) => new RegExp(name + ':\\\s+specifier: [\\\s\\\w\\\.^]+version: (\\\d+\\\.\\\d+\\\.\\\d+)');
+           const playwrightVersion = lockfile.match(pattern('playwright'))[1];
+           console.log('PLAYWRIGHT_VERSION=' + playwrightVersion);
+          "
+          )" >> $GITHUB_OUTPUT
+
+      - name: Print versions
+        shell: bash
+        run: echo "${{ toJson(steps.resolve-package-versions.outputs) }}"
+
+      - name: Check resolved package versions
+        shell: bash
+        if: |
+          contains(fromJSON('[null, "", "undefined"]'), steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION)
+        run: echo "Failed to resolve package versions. See log above." && exit 1
+
+      - name: Cache Playwright v${{ steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION }}
+        uses: actions/cache@v5
+        id: playwright-cache
+        with:
+          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
+          key: ${{ runner.os }}-playwright-${{ steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION }}
+          restore-keys: |
+            ${{ runner.os }}-playwright-
+
+      - name: Install Playwright Dependencies
+        shell: bash
+        if: steps.playwright-cache.outputs.cache-hit != 'true'
+        run: pnpm exec playwright install --with-deps --only-shell
+
       - name: Cache Playwright browsers
         uses: actions/cache@v4
         with:
           path: ~/.cache/ms-playwright
           key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml') }}
-
-      - name: Install Playwright browsers
-        run: pnpm --filter @vega-ui/react exec playwright install --with-deps
 
       - name: Run Tests
         run: pnpm test
